import os
from langchain_community.vectorstores.azuresearch import AzureSearch
from langchain_openai import AzureOpenAIEmbeddings

def retrieve_knowledge(queries: list) -> str:
    """Fetches relevant documents from Azure AI Search based on generated queries."""
    if not queries:
        return ""

    # 1. Initialize the same embeddings model
    embeddings = AzureOpenAIEmbeddings(
        azure_deployment=os.getenv("AZURE_OPENAI_EMBEDDING_DEPLOYMENT"),
        openai_api_version=os.getenv("AZURE_OPENAI_API_VERSION")
    )
    
    # 2. Connect to the existing Azure Index
    vector_store = AzureSearch(
        azure_search_endpoint=os.getenv("AZURE_SEARCH_ENDPOINT"),
        azure_search_key=os.getenv("AZURE_SEARCH_API_KEY"),
        index_name=os.getenv("AZURE_SEARCH_INDEX_NAME"),
        embedding_function=embeddings.embed_query,
    )
    
    retrieved_texts = []
    
    # 3. Perform a similarity search for each query generated by the RAG agent
    for query in queries:
        # k=3 fetches the top 3 most relevant chunks per query
        docs = vector_store.similarity_search(query, k=3)
        for doc in docs:
            retrieved_texts.append(doc.page_content)
            
    # 4. Deduplicate the results (in case different queries pulled the same chunk)
    unique_texts = list(set(retrieved_texts))
    
    # Return a single string formatted for the LLM context window
    return "\n\n---\n\n".join(unique_texts)