# ΥΠΕΥΘΥΝΟ ΓΙΑ ΝΑ ΚΑΝΕΙ QUERY ΤΟ VECTOR DATABASE ΜΑΣ
# ΓΙΑ ΤΩΡΑ ΘΑ ΕΧΟΥΜΕ ΕΝΑ LOCAL CHROMADB ΠΟΥ ΕΙΝΑΙ ΔΩΡΕΑΝ
# ΜΕΤΑ ΘΑ ΒΑΛΟΥΜΕ ΤΟ AZURE AI SEARCH ΠΟΥ ΜΑΣ ΔΙΝΟΥΝ ΜΑΛΛΟΝ
# ΔΕΝ ΞΕΡΩ ΤΙ ΜΑ ΔΙΝΟΥΝ ΑΚΡΙΒΩΣ ΤΟ ΒΛΕΠΟΥΜΕ

from langchain_community.vectorstores import Chroma
from langchain_google_genai import GoogleGenerativeAIEmbeddings
import os

# Define where Chroma will save its data on your local machine
CHROMA_PATH = "./knowledge_base/chroma_db"

def get_embedding_model():
    """Initializes the Gemini embedding model."""
    return GoogleGenerativeAIEmbeddings(model="gemini-embedding-001")

def get_vector_store():
    """Connects to the local ChromaDB instance."""
    return Chroma(
        persist_directory=CHROMA_PATH,
        embedding_function=get_embedding_model()
    )

def retrieve_knowledge(queries: list[str], k: int = 2) -> str:
    """
    Takes the queries generated by the Prompt Package, searches ChromaDB, 
    and combines the results into a single context string.
    """
    db = get_vector_store()
    retrieved_content = []
    
    # Run a search for each query the LLM generated
    for query in queries:
        # k=2 means grab the top 2 most relevant document chunks per query
        results = db.similarity_search(query, k=k) 
        for doc in results:
            retrieved_content.append(doc.page_content)
            
    # Remove duplicates in case multiple queries found the same document
    unique_content = list(set(retrieved_content))
    
    # Combine them into a single string for the final answer generator
    return "\n\n---\n\n".join(unique_content)